package com.lambdaherding.edi.ch05;

import java.util.stream.Stream;

/**
 * A list of countries
 */
public interface Countries {
	public static Stream<Country> all() {
		Continent africa = new Continent().name( "Africa" );
		Continent asia = new Continent().name( "Asia" );
		Continent europe = new Continent().name( "Europe" );
		Continent na = new Continent().name( "North America" );
		Continent sa = new Continent().name( "South America" );
		Continent oceania = new Continent().name( "Oceania" );

		return Stream.of(
				new Country().name( "Algeria" ).capital( "Algiers" ).continent( africa ),
				new Country().name( "Angola" ).capital( "Luanda" ).continent( africa ),
				new Country().name( "Benin" ).capital( "Porto Novo" ).continent( africa ),
				new Country().name( "Botswana" ).capital( "Gaborone" ).continent( africa ),
				new Country().name( "Burkina Faso" ).capital( "Ouagadougou" ).continent( africa ),
				new Country().name( "Burundi" ).capital( "Bujumbura" ).continent( africa ),
				new Country().name( "Cameroon" ).capital( "Yaoundé" ).continent( africa ),
				new Country().name( "Cape Verde" ).capital( "Praia" ).continent( africa ),
				new Country().name( "Chad" ).capital( "N'Djamena" ).continent( africa ),
				new Country().name( "Central African Republic" ).capital( "Bangui" ).continent( africa ),
				new Country().name( "Comoros" ).capital( "Moroni" ).continent( africa ),
				new Country().name( "Republic of the Congo" ).capital( "Brazzaville" ).continent( africa ),
				new Country().name( "Democratic Republic of the Congo" ).capital( "Kinshasa" ).continent( africa ),
				new Country().name( "Côte d'Ivoire" ).capital( "Yamoussoukro" ).continent( africa ),
				new Country().name( "Djibouti" ).capital( "Djibouti" ).continent( africa ),
				new Country().name( "Egypt" ).capital( "Cairo" ).continent( africa ),
				new Country().name( "Equatorial Guinea" ).capital( "Malabo" ).continent( africa ),
				new Country().name( "Eritrea" ).capital( "Asmara" ).continent( africa ),
				new Country().name( "Ethiopia" ).capital( "Addis Ababa" ).continent( africa ),
				new Country().name( "Gabon" ).capital( "Libreville" ).continent( africa ),
				new Country().name( "The Gambia" ).capital( "Banjul" ).continent( africa ),
				new Country().name( "Ghana" ).capital( "Accra" ).continent( africa ),
				new Country().name( "Guinea" ).capital( "Conakry" ).continent( africa ),
				new Country().name( "Guinea-Bissau" ).capital( "Bissau" ).continent( africa ),
				new Country().name( "Kenya" ).capital( "Nairobi" ).continent( africa ),
				new Country().name( "Lesotho" ).capital( "Maseru" ).continent( africa ),
				new Country().name( "Liberia" ).capital( "Monrovia" ).continent( africa ),
				new Country().name( "Libya" ).capital( "Tripoli" ).continent( africa ),
				new Country().name( "Madagascar" ).capital( "Antananarivo" ).continent( africa ),
				new Country().name( "Malawi" ).capital( "Lilongwe" ).continent( africa ),
				new Country().name( "Mali" ).capital( "Bamako" ).continent( africa ),
				new Country().name( "Mauritania" ).capital( "Nouakchott" ).continent( africa ),
				new Country().name( "Mauritius" ).capital( "Port Louis" ).continent( africa ),
				new Country().name( "Morocco" ).capital( "Rabat" ).continent( africa ),
				new Country().name( "Mozambique" ).capital( "Maputo" ).continent( africa ),
				new Country().name( "Namibia" ).capital( "Windhoek" ).continent( africa ),
				new Country().name( "Niger" ).capital( "Niamey" ).continent( africa ),
				new Country().name( "Nigeria" ).capital( "Abuja" ).continent( africa ),
				new Country().name( "Rwanda" ).capital( "Kigali" ).continent( africa ),
				new Country().name( "São Tomé and Príncipe" ).capital( "São Tomé" ).continent( africa ),
				new Country().name( "Senegal" ).capital( "Dakar" ).continent( africa ),
				new Country().name( "Seychelles" ).capital( "Victoria" ).continent( africa ),
				new Country().name( "Sierra Leone" ).capital( "Freetown" ).continent( africa ),
				new Country().name( "Somalia" ).capital( "Mogadishu" ).continent( africa ),
				new Country().name( "South Africa" ).capital( "Pretoria" ).continent( africa ),
				new Country().name( "South Sudan" ).capital( "Juba" ).continent( africa ),
				new Country().name( "Sudan" ).capital( "Khartoum" ).continent( africa ),
				new Country().name( "Swaziland" ).capital( "Mbabane" ).continent( africa ),
				new Country().name( "Tanzania" ).capital( "Dodoma" ).continent( africa ),
				new Country().name( "Togo" ).capital( "Lome" ).continent( africa ),
				new Country().name( "Tunisia" ).capital( "Tunis" ).continent( africa ),
				new Country().name( "Uganda" ).capital( "Kampala" ).continent( africa ),
				new Country().name( "Zambia" ).capital( "Lusaka" ).continent( africa ),
				new Country().name( "Zimbabwe" ).capital( "Harare" ).continent( africa ),

				new Country().name( "Afghanistan" ).capital( "Kabul" ).continent( asia ),
				new Country().name( "Armenia" ).capital( "Yerevan" ).continent( asia ),
				new Country().name( "Azerbaijan" ).capital( "Baku" ).continent( asia ),
				new Country().name( "Bahrain" ).capital( "Manama" ).continent( asia ),
				new Country().name( "Bangladesh" ).capital( "Dhaka" ).continent( asia ),
				new Country().name( "Bhutan" ).capital( "Thimphu" ).continent( asia ),
				new Country().name( "Brunei" ).capital( "Bandar Seri Begawan" ).continent( asia ),
				new Country().name( "Cambodia" ).capital( "Phnom Penh" ).continent( asia ),
				new Country().name( "China" ).capital( "Beijing" ).continent( asia ),
				new Country().name( "Taiwan" ).capital( "Taipei" ).continent( asia ),
				new Country().name( "East Timor" ).capital( "Dili" ).continent( asia ),
				new Country().name( "India" ).capital( "New Delhi" ).continent( asia ),
				new Country().name( "Indonesia" ).capital( "Jakarta" ).continent( asia ),
				new Country().name( "Iran" ).capital( "Tehran" ).continent( asia ),
				new Country().name( "Iraq" ).capital( "Baghdad" ).continent( asia ),
				new Country().name( "Israel" ).capital( "Jerusalem" ).continent( asia ),
				new Country().name( "Palestine" ).capital( "Gaza" ).continent( asia ),
				new Country().name( "Japan" ).capital( "Tokyo" ).continent( asia ),
				new Country().name( "Jordan" ).capital( "Amman" ).continent( asia ),
				new Country().name( "Kazakhstan" ).capital( "Astana" ).continent( asia ),
				new Country().name( "Kuwait" ).capital( "Kuwait" ).continent( asia ),
				new Country().name( "Kyrgyzstan" ).capital( "Bishkek" ).continent( asia ),
				new Country().name( "Laos" ).capital( "Vientiane" ).continent( asia ),
				new Country().name( "Lebanon" ).capital( "Beirut" ).continent( asia ),
				new Country().name( "Malaysia" ).capital( "Kuala Lumpur" ).continent( asia ),
				new Country().name( "Maldives" ).capital( "Malé" ).continent( asia ),
				new Country().name( "Mongolia" ).capital( "Ulaanbaatar" ).continent( asia ),
				new Country().name( "Myanmar" ).capital( "Naypyidaw" ).continent( asia ),
				new Country().name( "Nepal" ).capital( "Kathmandu" ).continent( asia ),
				new Country().name( "North Korea" ).capital( "Pyongyang" ).continent( asia ),
				new Country().name( "Oman" ).capital( "Muscat" ).continent( asia ),
				new Country().name( "Pakistan" ).capital( "Islamabad" ).continent( asia ),
				new Country().name( "Philippines" ).capital( "Manila" ).continent( asia ),
				new Country().name( "Qatar" ).capital( "Doha" ).continent( asia ),
				new Country().name( "Saudi Arabia" ).capital( "Riyadh" ).continent( asia ),
				new Country().name( "Singapore" ).capital( "Singapore" ).continent( asia ),
				new Country().name( "South Korea" ).capital( "Seoul" ).continent( asia ),
				new Country().name( "Sri Lanka" ).capital( "Colombo" ).continent( asia ),
				new Country().name( "Syria" ).capital( "Damascus" ).continent( asia ),
				new Country().name( "Tajikistan" ).capital( "Dushanbe" ).continent( asia ),
				new Country().name( "Thailand" ).capital( "Bangkok" ).continent( asia ),
				new Country().name( "Turkey" ).capital( "Ankara" ).continent( asia ),
				new Country().name( "Turkmenistan" ).capital( "A\u015fgabat" ).continent( asia ),
				new Country().name( "United Arab Emirates" ).capital( "Abu Dhabi" ).continent( asia ),
				new Country().name( "Uzbekistan" ).capital( "Tashkent" ).continent( asia ),
				new Country().name( "Vietnam" ).capital( "Hanoi" ).continent( asia ),
				new Country().name( "Yemen" ).capital( "Sana'a" ).continent( asia ),

				new Country().name( "Albania" ).capital( "Tirana" ).continent( europe ),
				new Country().name( "Andorra" ).capital( "Andorra la Vella" ).continent( europe ),
				new Country().name( "Austria" ).capital( "Vienna" ).continent( europe ),
				new Country().name( "Belarus" ).capital( "Minsk" ).continent( europe ),
				new Country().name( "Belgium" ).capital( "Brussels" ).continent( europe ),
				new Country().name( "Bosnia and Herzegovina" ).capital( "Sarajevo" ).continent( europe ),
				new Country().name( "Bulgaria" ).capital( "Sofia" ).continent( europe ),
				new Country().name( "Croatia" ).capital( "Zagreb" ).continent( europe ),
				new Country().name( "Cyprus" ).capital( "Nicosia" ).continent( europe ),
				new Country().name( "Czech Republic" ).capital( "Prague" ).continent( europe ),
				new Country().name( "Denmark" ).capital( "Copenhagen" ).continent( europe ),
				new Country().name( "Estonia" ).capital( "Tallinn" ).continent( europe ),
				new Country().name( "Finland" ).capital( "Helsinki" ).continent( europe ),
				new Country().name( "France" ).capital( "Paris" ).continent( europe ),
				new Country().name( "Germany" ).capital( "Berlin" ).continent( europe ),
				new Country().name( "Greece" ).capital( "Athens" ).continent( europe ),
				new Country().name( "Hungary" ).capital( "Budapest" ).continent( europe ),
				new Country().name( "Iceland" ).capital( "Reykjavik" ).continent( europe ),
				new Country().name( "Republic of Ireland" ).capital( "Dublin" ).continent( europe ),
				new Country().name( "Italy" ).capital( "Rome" ).continent( europe ),
				new Country().name( "Latvia" ).capital( "Riga" ).continent( europe ),
				new Country().name( "Liechtenstein" ).capital( "Vaduz" ).continent( europe ),
				new Country().name( "Lithuania" ).capital( "Vilnius" ).continent( europe ),
				new Country().name( "Luxembourg" ).capital( "Luxembourg City" ).continent( europe ),
				new Country().name( "Macedonia" ).capital( "Skopje" ).continent( europe ),
				new Country().name( "Malta" ).capital( "Valletta" ).continent( europe ),
				new Country().name( "Moldova" ).capital( "Chisinau" ).continent( europe ),
				new Country().name( "Monaco" ).capital( "Monaco" ).continent( europe ),
				new Country().name( "Montenegro" ).capital( "Podgorica" ).continent( europe ),
				new Country().name( "Netherlands" ).capital( "Amsterdam" ).continent( europe ),
				new Country().name( "Norway" ).capital( "Oslo" ).continent( europe ),
				new Country().name( "Poland" ).capital( "Warsaw" ).continent( europe ),
				new Country().name( "Portugal" ).capital( "Lisbon" ).continent( europe ),
				new Country().name( "Romania" ).capital( "Bucharest" ).continent( europe ),
				new Country().name( "Russia" ).capital( "Moscow" ).continent( europe ),
				new Country().name( "San Marino" ).capital( "San Marino" ).continent( europe ),
				new Country().name( "Serbia" ).capital( "Belgrade" ).continent( europe ),
				new Country().name( "Slovakia" ).capital( "Bratislava" ).continent( europe ),
				new Country().name( "Slovenia" ).capital( "Ljubljana" ).continent( europe ),
				new Country().name( "Spain" ).capital( "Madrid" ).continent( europe ),
				new Country().name( "Sweden" ).capital( "Stockholm" ).continent( europe ),
				new Country().name( "Switzerland" ).capital( "Bern" ).continent( europe ),
				new Country().name( "Ukraine" ).capital( "Kyiv" ).continent( europe ),
				new Country().name( "United Kingdom" ).capital( "London" ).continent( europe ),
				new Country().name( "Vatican City" ).capital( "Vatican City" ).continent( europe ),

				new Country().name( "Canada" ).capital( "Ottawa" ).continent( na ),
				new Country().name( "Greenland" ).capital( "Nuuk" ).continent( na ),
				new Country().name( "Mexico" ).capital( "Mexico City" ).continent( na ),
				new Country().name( "United States" ).capital( "Washington DC" ).continent( na ),
				new Country().name( "Antigua and Barbuda" ).capital( "St. John's" ).continent( na ),
				new Country().name( "Bahamas" ).capital( "Nassau" ).continent( na ),
				new Country().name( "Barbados" ).capital( "Bridgetown" ).continent( na ),
				new Country().name( "Belize" ).capital( "Belmopan" ).continent( na ),
				new Country().name( "Costa Rica" ).capital( "San José" ).continent( na ),
				new Country().name( "Cuba" ).capital( "Havana" ).continent( na ),
				new Country().name( "Dominica" ).capital( "Roseau" ).continent( na ),
				new Country().name( "Dominican Republic" ).capital( "Santo Domingo" ).continent( na ),
				new Country().name( "El Salvador" ).capital( "San Salvador" ).continent( na ),
				new Country().name( "Grenada" ).capital( "St George's" ).continent( na ),
				new Country().name( "Guatemala" ).capital( "Guatemala" ).continent( na ),
				new Country().name( "Haiti" ).capital( "Port-au-Prince" ).continent( na ),
				new Country().name( "Honduras" ).capital( "Tegucigalpa" ).continent( na ),
				new Country().name( "Jamaica" ).capital( "Kingston, Jamaica" ).continent( na ),
				new Country().name( "Nicaragua" ).capital( "Managua" ).continent( na ),
				new Country().name( "Panama" ).capital( "Panama City" ).continent( na ),
				new Country().name( "Puerto Rico" ).capital( "San Juan" ).continent( na ),
				new Country().name( "Saint Kitts and Nevis" ).capital( "Basseterre" ).continent( na ),
				new Country().name( "Saint Lucia" ).capital( "Castries" ).continent( na ),
				new Country().name( "Saint Vincent and the Grenadines" ).capital( "Kingstown" ).continent( na ),
				new Country().name( "Trinidad and Tobago" ).capital( "Port of Spain" ).continent( na ),
				new Country().name( "Turks and Caicos" ).capital( "Cockburn Town" ).continent( na ),

				new Country().name( "Argentina" ).capital( "Buenos Aires" ).continent( sa ),
				new Country().name( "Bolivia" ).capital( "La Paz" ).continent( sa ),
				new Country().name( "Brazil" ).capital( "Brasília" ).continent( sa ),
				new Country().name( "Chile" ).capital( "Santiago" ).continent( sa ),
				new Country().name( "Colombia" ).capital( "Bogotá" ).continent( sa ),
				new Country().name( "Ecuador" ).capital( "Quito" ).continent( sa ),
				new Country().name( "French Guiana" ).capital( "Cayenne" ).continent( sa ),
				new Country().name( "Guyana" ).capital( "Georgetown" ).continent( sa ),
				new Country().name( "Paraguay" ).capital( "Asuncion" ).continent( sa ),
				new Country().name( "Peru" ).capital( "Lima" ).continent( sa ),
				new Country().name( "Suriname" ).capital( "Paramaribo" ).continent( sa ),
				new Country().name( "Uruguay" ).capital( "Montevideo" ).continent( sa ),
				new Country().name( "Venezuela" ).capital( "Caracas" ).continent( sa ),

				new Country().name( "Australia" ).capital( "Canberra" ).continent( oceania ),
				new Country().name( "New Zealand" ).capital( "Wellington" ).continent( oceania ),
				new Country().name( "Fiji" ).capital( "Suva" ).continent( oceania ),
				new Country().name( "Papua New Guinea" ).capital( "Port Moresby" ).continent( oceania ),
				new Country().name( "Solomon Islands" ).capital( "Honiara" ).continent( oceania ),
				new Country().name( "Vanuatu" ).capital( "Port Vila" ).continent( oceania ),
				new Country().name( "Kiribati" ).capital( "South Tarawa" ).continent( oceania ),
				new Country().name( "Marshall Islands" ).capital( "Majuro" ).continent( oceania ),
				new Country().name( "Micronesia" ).capital( "Palikir" ).continent( oceania ),
				new Country().name( "Nauru" ).capital( "Yaren" ).continent( oceania ),
				new Country().name( "Palau" ).capital( "Koror" ).continent( oceania ),
				new Country().name( "Samoa" ).capital( "Apia" ).continent( oceania ),
				new Country().name( "Tonga" ).capital( "Nuku'alofa" ).continent( oceania ),
				new Country().name( "Tuvalu" ).capital( "Funafuti" ).continent( oceania ) );
	}
}
